modal
SG-SantiagoGilgorri/Tickets-App pull request #2
Opened 2023-07-11 04:27 UTC by SG-SantiagoGilgorri

Amigoooo pude poner el modal y acomodarlo a un tamaño considerable para meterle informacion....... ahora me encontre con un inconvieniente que es.....  creo un  modal distinto para cada evento o la idea seria que haga un formulario y que la informacion de los campos este guardada en una base de datos? porque nose como continuar en verdad

2023-07-11 14:04 UTC, joacoc commented
Fijate que el tamaño del modal es muuuy grande.
La idea es que hagas un solo modal, donde metas la informacion que necesites. Si ves que el modal no te sirve o es muy grande. Agregale el boton de agregar al carrito directamente a la imagen del evento! (KISS)

<img width="852" alt="Screenshot 2023-07-11 at 16 03 10" src="https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/11491779/d9f300b8-81b8-42eb-8aec-14d4b2f06177">

2023-07-11 15:23 UTC, SG-SantiagoGilgorri commented
Amigo consulta, yo tendria que hacer un template para mi modal, con una base de datos, cosa que cuando toque diferentes eventos se abra el modal y muestre info de dicho evento verdad?

o tendria que hacer un modal diferente para cada evento. que me recomendas hacer?

2023-07-11 17:17 UTC, joacoc commented
Es un único modal para todos los eventos. Adentro del modal cargas la info del evento

2023-07-11 17:17 UTC, joacoc commented on app/components/modal.js
> +  return (
Aca por ejemplo podría buscar toda la info del evento.

2023-07-11 17:27 UTC, SG-SantiagoGilgorri commented on app/components/modal.js
> +  return (
Amigo ahi arme maso menos un boceto del modal, cargue yo los datos a manopla. decime que te parece o que le modifico

2023-07-11 19:29 UTC, joacoc commented
@SG-SantiagoGilgorri Muy bueno el modal. Cada evento tendría que abrir el modal con los datos del evento. Se los deberías pasar por parámetro. El modal debería aceptar props (parametros) con la info del evento.

2023-07-11 21:12 UTC, SG-SantiagoGilgorri commented
Amigo ahi logre que el modal me muestre la data especifica de dicho evento al clickear y tmb le di funcion de cierre al button cancel asi como apretando ESC, mañana voy a hacer la funcionalidad que agregue al carrito los tickets cuando le de a a aceptar pero te queria hacer unas consultas respecto al tema

2023-07-12 07:02 UTC, joacoc commented
Sos un capo!!! Te quedo excelente. Hay que darle un mejor estilo al contenido del modal.

[1. Podes usar este](https://tailwindui.com/components/application-ui/data-display/description-lists#component-d9372707af2e94e67936e94d7339cbb3)

[2. O este que te dejo este acá](https://tailwindui.com/components/application-ui/data-display/description-lists#component-abf967b89e0df5cf9648be5a30d7660e):

```javascript
import { CalendarDaysIcon, CreditCardIcon, UserCircleIcon } from '@heroicons/react/20/solid'

export default function Example() {
  return (
    <div className="lg:col-start-3 lg:row-end-1">
      <h2 className="sr-only">Summary</h2>
      <div className="rounded-lg bg-gray-50 shadow-sm ring-1 ring-gray-900/5">
        <dl className="flex flex-wrap">
          <div className="flex-auto pl-6 pt-6">
            <dt className="text-sm font-semibold leading-6 text-gray-900">Amount</dt>
            <dd className="mt-1 text-base font-semibold leading-6 text-gray-900">$10,560.00</dd>
          </div>
          <div className="flex-none self-end px-6 pt-4">
            <dt className="sr-only">Status</dt>
            <dd className="inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">
              Paid
            </dd>
          </div>
          <div className="mt-6 flex w-full flex-none gap-x-4 border-t border-gray-900/5 px-6 pt-6">
            <dt className="flex-none">
              <span className="sr-only">Client</span>
              <UserCircleIcon className="h-6 w-5 text-gray-400" aria-hidden="true" />
            </dt>
            <dd className="text-sm font-medium leading-6 text-gray-900">Alex Curren</dd>
          </div>
          <div className="mt-4 flex w-full flex-none gap-x-4 px-6">
            <dt className="flex-none">
              <span className="sr-only">Due date</span>
              <CalendarDaysIcon className="h-6 w-5 text-gray-400" aria-hidden="true" />
            </dt>
            <dd className="text-sm leading-6 text-gray-500">
              <time dateTime="2023-01-31">January 31, 2023</time>
            </dd>
          </div>
          <div className="mt-4 flex w-full flex-none gap-x-4 px-6">
            <dt className="flex-none">
              <span className="sr-only">Status</span>
              <CreditCardIcon className="h-6 w-5 text-gray-400" aria-hidden="true" />
            </dt>
            <dd className="text-sm leading-6 text-gray-500">Paid with MasterCard</dd>
          </div>
        </dl>
        <div className="mt-6 border-t border-gray-900/5 px-6 py-6">
          <a href="#" className="text-sm font-semibold leading-6 text-gray-900">
            Download receipt <span aria-hidden="true">&rarr;</span>
          </a>
        </div>
      </div>
    </div>
  )
}
```

Add tickets esta aun poco desalineado:
<img width="329" alt="Screenshot 2023-07-12 at 09 01 34" src="https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/11491779/e138b56f-28fd-4031-8e17-b312636e5e14">

2023-07-12 07:03 UTC, joacoc commented
Una vez arreglado el estilo, apruebo el PR y va a estar listo para merg.

2023-07-12 20:52 UTC, joacoc requested changes

2023-07-12 20:52 UTC, joacoc commented on app/components/modal.js
> +            className="inline-flex w-full justify-center rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500 sm:ml-3 sm:w-auto"
Las acciones positivas, se usa color verde. Para las destructivas o peligrosas, o estilo cancelar, rojo.

Siempre utiliza un color bajo (~300) `bg-...-300` para el color normal y un color mas alto (~500/600) `bg-...-600` para cuando se hace el hover. 
```suggestion
            className="inline-flex w-full justify-center rounded-md bg-green-300 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-green-500 sm:ml-3 sm:w-auto"
```

2023-07-12 20:52 UTC, joacoc commented on app/components/modal.js
> +    <div className="fixed inset-0 flex items-center justify-center z-50">
Te digo que quedaba mejor en vertical! Por que las imágenes que utilizas son verticales. Si las imágenes van a ser verticales déjalo como esta, sino antes quedaba mejor

2023-07-12 20:52 UTC, joacoc commented on app/components/modal.js
> +              <dd className="ml-1 text-sm leading-6 text-gray-700">
Esta parte se sigue viendo rara. Como que no esta alineada verticalmente los tamaños.

2023-07-12 20:52 UTC, joacoc commented on app/components/modal.js
> +              <UserCircleIcon
En vez de `UserCircleIcon` utiliza alguno al estilo Map (E.g. `map-pin` probablemente se llame `MapPinIcon`)

2023-07-12 20:52 UTC, joacoc commented on app/components/modal.js
> +              <dd className="ml-1 text-sm leading-6 text-gray-700">
Al tener un `NumericInput` (que ya trae para subir y bajar la cantidad, para que esta los botones? KISS)

2023-07-12 20:54 UTC, joacoc commented on app/components/modal.js
> +            className="inline-flex w-full justify-center rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500 sm:ml-3 sm:w-auto"
Esto es para crear un efecto mas atractivo cuando pasas el mouse por arriba.

2023-07-13 03:07 UTC, SG-SantiagoGilgorri commented
A ver amiguitoooo si me mergeass el pull request? jajajaj . creo que le cambiaria un poco el tamaño de los campos, lo estoy viendo al 100% del browser y siento que quizas este chiquito pero espero tu opinion

2023-07-13 08:25 UTC, joacoc approved these changes
Jajaja. Ultimo. Te lo dejo aprobado para cuando este fixeado lo siguiente:

<img width="216" alt="Screenshot 2023-07-13 at 10 24 00" src="https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/11491779/4f724437-c9dd-435d-ab76-48f31492c32c">

Respecto a los colores, me equivoque, era al revez, valor alto cuando esta sin hover, valor bajo cuando esta con hover.

2023-07-13 08:25 UTC, joacoc commented on app/components/modal.js
> +            className="inline-flex w-full justify-center rounded-md bg-green-300 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-green-500 sm:ml-3 sm:w-auto"
```suggestion
            className="inline-flex w-full justify-center rounded-md bg-green-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-green-500 sm:ml-3 sm:w-auto"
```

2023-07-13 12:58 UTC, SG-SantiagoGilgorri commented
Request Done amigo

2023-07-13 14:01 UTC, joacoc commented on app/components/modal.js
> +            className="inline-flex w-full justify-center rounded-md bg-green-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-green-300 sm:ml-3 sm:w-auto"
```suggestion
            className="inline-flex w-full justify-center rounded-md bg-green-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-green-500 sm:ml-3 sm:w-auto"
```

2023-07-13 17:25 UTC, SG-SantiagoGilgorri commented
amigo pero yo en el input de los tickets saque los botones esos como me pediste con esta linea

https://github.com/SG-SantiagoGilgorri/Tickets-App/blob/fbb1e04116fff04cff60a43c7db01989a72d7172/app/components/ticketcounter.js#L39

y despues le ajuste el tamaño para que queden iguales los botones con el input.. no logro encontrar el porque se te ve asi

2023-07-13 20:06 UTC, joacoc commented
Funciona bien en el Chrome pero mal en el Safari. Igual mergiemos!

2023-07-13 20:07 UTC, merged