LinkGoogleMaps
SG-SantiagoGilgorri/Tickets-App pull request #3
Opened 2023-07-13 20:34 UTC by SG-SantiagoGilgorri

Amigoooo ahora si deje todo al dia, y despues de esto del LInk seguimos con este branch y el Cart

2023-07-14 14:04 UTC, SG-SantiagoGilgorri commented
Amigooooo pude lograrlo, lo que si antes de empezar a tocar lo visual queria el visto bueno de la funcionalidad. acepto sugerencias o que me propones de agregarle al DrowpDown y tmb que podria hacer para que el icono del cart figure con notificaciones.
Habia pensado o signo de exclamación, que cambie de color o que figure con un numero de notificacion tipo 1 o 2 dependiendo de cuantas cosas tenga agregado

2023-07-14 20:54 UTC, SG-SantiagoGilgorri commented
Amigooo agregue notificaciones al carrito y tenia un problema que no se ponia bien la quantity de entradas en el dropdown.

ahora lo proximo seria agregar un boton para borrar del carrito y otro que redireccione a la pasarella de pagos

2023-07-17 20:28 UTC, SG-SantiagoGilgorri commented
bueno amigooo hice lo hablado en la call de hoy:
1ro: agregue un icono de trash que borra el evento
2do: agregue un button para el checkout
3ro: pude hacer el ajuste para que cuando mande x cantidad de tickets, dentro del cart, en el input para modificar aparece la cantidad mandada, 
4ro: agregue botones para modificar los tickets

PD: no use el selectMenu alfinal jajaja

2023-07-17 20:32 UTC, joacoc commented
Deberia estar en ingles:
<img width="495" alt="Screenshot 2023-07-17 at 22 28 58" src="https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/11491779/8f7861e3-6613-4214-ba5d-7698144eb536">

Tendria que poder apretar y que me mande al Home (la pantalla que dice _Get Started_) 
<img width="227" alt="Screenshot 2023-07-17 at 22 29 20" src="https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/11491779/9afa67a1-c1db-4843-9a13-de24276a99db">


Elegí y utiliza solo uno de los dos:
<img width="226" alt="Screenshot 2023-07-17 at 22 29 53" src="https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/11491779/ec82730d-3a49-4499-b365-05aa6638059c">

<img width="113" alt="Screenshot 2023-07-17 at 22 30 16" src="https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/11491779/85b37e4f-a5d7-424e-a0c4-74bf67d7e4a6">


"CheckOut" -> "Check out"
<img width="375" alt="Screenshot 2023-07-17 at 22 30 08" src="https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/11491779/8732233f-10ec-4102-a57b-77879b3a5018">


Y por supuesto ahora que me lo mencionaste, estos tienen que estar alineados:
<img width="375" alt="Screenshot 2023-07-17 at 22 31 56" src="https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/11491779/4776d2f7-4938-4792-85c0-cb8692edc50f">

2023-07-17 20:34 UTC, joacoc requested changes

2023-07-17 20:34 UTC, joacoc commented on app/components/cartcontext.js
> +    if (existingItem) {
Buenisimo!

2023-07-17 21:42 UTC, SG-SantiagoGilgorri commented
Amigoooo pude hacer todo menos lo de alinear todos los eventos, me vas a tener que ayudar con esa

2023-07-18 09:24 UTC, joacoc commented on app/components/navbar.js
> +                            className=" w-20 h-20 mr-2 object-cover"
```suggestion
                            className=" w-10 h-10 mr-2 object-cover"
```

2023-07-18 19:59 UTC, joacoc commented
@SG-SantiagoGilgorri falta que aparezcan los precios en el modal del checkout!

2023-07-19 04:44 UTC, SG-SantiagoGilgorri commented
uhhh amigo no sabes lo que me costo.... me hizo renegar bocha. pero bueno ahi salio ya avisame que mas tengo que ajustar mañana

2023-07-19 07:25 UTC, joacoc commented
Dejo el review en forma de video hoy!
https://www.loom.com/share/4323f1e689d5491fa3140e869483a4f8

2023-07-19 19:57 UTC, SG-SantiagoGilgorri commented
Amigooo..... finally  me tuvo loco, hace rato que algo no me costaba tanto

2023-07-20 07:10 UTC, joacoc approved these changes
Te dejo unos detalles. Faltaría volver arreglar las imágenes que deje un comment de como hacerlo. Y una vez que este ya estaría listo para mergear!

2023-07-20 07:10 UTC, joacoc commented on app/components/navbar.js
> +                                <span>Total:</span>
```suggestion
```

2023-07-20 07:10 UTC, joacoc commented on app/components/navbar.js
> +                                <span>Total:</span>
Queda mejor sin el total

2023-07-20 07:10 UTC, joacoc commented on app/components/navbar.js
> +                          <img
Aca estaba el fix que había aplicado. Fíjate el commit que hice, que te figuran los cambios y volvelo a aplicar!

2023-07-20 07:10 UTC, joacoc commented on app/components/navbar.js
> +                            <p className="font-medium">{item.title}</p>
```suggestion
                            <p className="font-light">{item.title}</p>
```

2023-07-20 07:10 UTC, joacoc commented on app/components/navbar.js
> +                            Total: ${calculateTotalPrice()}
```suggestion
                            Total: <span className="font-bold"><${calculateTotalPrice()}</span>
```

2023-07-20 07:10 UTC, joacoc commented on app/components/navbar.js
> +                            Total: ${calculateTotalPrice()}
Mas bold que el resto

2023-07-20 07:11 UTC, joacoc approved these changes

2023-07-20 07:11 UTC, joacoc commented on app/components/navbar.js
> +                          <p className="font-medium">
```suggestion
                          <p className="font-light">
```

2023-07-20 13:24 UTC, SG-SantiagoGilgorri commented
Listorti los request amigooo!!!!. con que deberia proseguir ahora?

2023-07-20 21:12 UTC, joacoc commented
Fijate que las imagenes siguen sin estar alineadas :(
<img width="368" alt="Screenshot 2023-07-20 at 23 11 38" src="https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/11491779/cd02750b-e64a-42f2-b818-c95cd992f247">

Lo siguiente seria que el checkout te mande a Mercado Pago!

2023-07-20 21:12 UTC, joacoc commented
Si ves que no sale hacemos una call! Mañana estoy bastante libre.

2023-07-20 21:18 UTC, joacoc commented on app/components/navbar.js
> +                          className="inline-flex w-full justify-center rounded-md bg-green-600 px-2 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-green-500 sm:ml-3 sm:w-auto"
```suggestion
                          className="inline-flex w-full justify-center rounded-md bg-green-600 px-2 py-2 text-sm font-semibold text-white shadow-sm hover:bg-green-500 sm:ml-3 sm:w-auto"
```

2023-07-21 07:33 UTC, merged