Ajustes
SG-SantiagoGilgorri/Tickets-App pull request #4
Opened 2023-07-21 17:12 UTC by SG-SantiagoGilgorri

Amigoo abro este Branch para empezar con lo de la pasarela de pago. y en ese pull request que hago ajuste algunas cositas visuales y experiencia usuario que note.

-Ajuste los textos dentro de los contenedores de los eventos para que queden iguales.

-Agregue que el carrito se cierre cuando se haga click fuera de el.

-alinie los textos y las imagenes de mi carrito

-note que cuando se cerraba el modal (asi sea cerrandolo o agregando entradas al carrito) volvia al principio de la pagina y no desde estaba el scrollBar al momento de abrir el modal.

2023-07-21 21:39 UTC, joacoc commented on app/components/modal.js
> +                  {event.price}$
```suggestion
                  ${event.price}
```

2023-07-21 21:39 UTC, joacoc commented on app/components/navbar.js
> +  useEffect(() => {
Interesante approach

2023-07-21 21:39 UTC, joacoc commented on app/events/page.js
> +                  title: "Blow pres.Olga korol @ WallMapu - Niceto vega",
```suggestion
                  title: "Blow pres.Olga korol @ WallMapu - Niceto Vega",
```

2023-07-21 21:39 UTC, joacoc commented on app/events/page.js
> +    window.scrollTo(0, scrollPosition);
Por que el `scrollTo(0, ..)`?

2023-07-21 22:36 UTC, SG-SantiagoGilgorri commented on app/events/page.js
> +    window.scrollTo(0, scrollPosition);
porque si yo tengo el scrollbar abajo y abro un modal, despues cuando lo cierra no me vuelve a la posicion en la que estaba, te lo vuelve al comienzo de la pagina

2023-07-24 07:39 UTC, joacoc commented on app/events/page.js
> +    window.scrollTo(0, scrollPosition);
Cuando se cierra el modal te tendria que deja el fondo donde estaba! De lo contrario la accion se vuelve un poco confusa.

2023-07-24 22:13 UTC, SG-SantiagoGilgorri commented
bueno amigo hice la direccion /checkout en mi pagina y le hice link con el button checkout dentro del dropdown del carrito.

tambien le di condicion para que no figure el cart en esa direccion,  pude agregar los 2 formularios y le removi algunos campos.

estuve viendo ahi en tailwind los Order summaries pero no me dejo usar el codigo, estaria para implementarlo

2023-07-25 08:37 UTC, joacoc commented
Review otra vez en [forma de loom!](https://www.loom.com/share/76afad6a7dfc49bfad7bcbbb400ed7e7)

2023-07-26 03:31 UTC, SG-SantiagoGilgorri commented
Amigo ajuste todo lo que me pediste en le request y estoy tratando de asemejarlo a este, 
![imagen](https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/129072570/c3f29c06-f09d-4124-93ff-aa5df3d1f1fe)

esta bastante verde y seguro con mil errores, espero criticas y sugerencias para mejorarlo

2023-07-26 11:19 UTC, joacoc commented
Dale. Fijate que la distribucion del form tambien es distinta. El first name y last name no estan includios.

Cancel no hace falta.
<img width="164" alt="Screenshot 2023-07-26 at 13 17 59" src="https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/11491779/5047ae96-dca7-4ea6-a039-4a10fe853f2b">

Aca faltaria controlar que el texto no te haga el deslineamiento que aparece abajo. Y tambien el titulo de "Credit. card details"
<img width="759" alt="Screenshot 2023-07-26 at 13 18 35" src="https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/11491779/67d93649-ce44-4ad0-af75-6149566e1279">

2023-07-26 11:21 UTC, joacoc commented
El height del summary (lo que tiene el background naranja) tambien tiene que llegar hasta el final
<img width="533" alt="Screenshot 2023-07-26 at 13 20 46" src="https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/11491779/b6fae9e6-0c9d-4f94-8b80-7ec144736c87">

2023-07-27 04:04 UTC, SG-SantiagoGilgorri commented
Bueno amigo buen dia para vos jejeje, cuchame ahi estuve Inspeccionando y tratando de hacer un esqueleto del order summary, decime que tengo que modificarle o si no te cierra  del todo me busco otro.

2023-07-27 07:25 UTC, joacoc commented on app/components/formdos.js
> +              className="rounded-md bg-orange-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-orange-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2
```suggestion
              className="w-full rounded-md bg-orange-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-orange-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-orange-600"
```

2023-07-27 07:29 UTC, joacoc commented on app/components/formuno.js
> +    <div className="mt-16 ml-52 mr-12 bg-orange-300 rounded-lg">
```suggestion
    <div className="pt-16 pl-52 pr-12 bg-slate-50 rounded-lg">
```

2023-07-27 07:30 UTC, joacoc commented on app/components/formdos.js
> +              <div className="sm:col-span-3">
Fletear

2023-07-27 07:30 UTC, joacoc commented on app/components/formdos.js
> +              <div className="sm:col-span-3">
Fletear last name

2023-07-27 07:30 UTC, joacoc commented on app/components/formdos.js
> +              <div className="sm:col-span-3">
Fletear phone

2023-07-27 07:31 UTC, joacoc commented
Aparte dejo un video de review con lo que estaba intentando hacer!

https://www.loom.com/share/eb31a42a96b24a0f90b0e7f7f79fb1b5

2023-07-27 15:44 UTC, SG-SantiagoGilgorri commented on app/components/formdos.js
> +              <div className="sm:col-span-3">
Amigo pero si fleteo esto se me rompe la distribucion del formulario. o tengo que envolverlo en un solo div y ahi aplico el CSS?

2023-07-27 17:09 UTC, SG-SantiagoGilgorri commented on app/components/formdos.js
> +              <div className="sm:col-span-3">
Amigo pero si fleteo esto se me rompe la distribucion del formulario

2023-07-27 17:32 UTC, SG-SantiagoGilgorri commented on app/components/navbar.js
> +  useEffect(() => {
Amigo ahi me acorde tuve que hacer eso porque sino me saltaba este error y lo solucione aplicando el useEffect

pero cuando modifico a tu manera me salta esto:

![imagen](https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/129072570/98dca24e-c27a-49f6-82de-bbcc5c835734)


por lo visto no afecta el uso de la pagina pero dime tu

2023-07-27 17:54 UTC, joacoc commented
@SG-SantiagoGilgorri por donde esta adjuntado el error? No tengo acceso a Vercel :(

2023-07-27 18:06 UTC, joacoc commented
Ahi lo corri localmente.

1. Cuando te salta:

`Error: Cannot find module '@tailwindcss/forms'`

Significa que falta instalar el modulo entre comillas.

Se soluciona con:
`npm install @tailwindcss/forms`

2. Cuando te salta:

ReferenceError: window is not defined

Significa que la variable "window" no esta declarada. Osea NextJS no la creo.

Este en algunos casos es fácil de resolver, en otros no. En este caso es uno de esos donde NextJS/Vercel cambia las cosas seguido. Así que hay que reemplazar por esto:

```javascript
import { usePathname } from 'next/navigation'
...
...
    const pathName = usePathname();
    const isCheckout = pathName === "/checkout";
```

Pusheo los fixes. Pullealos!

2023-07-27 18:09 UTC, joacoc requested changes

2023-07-27 18:09 UTC, joacoc commented on app/components/formsummary.js
> +        <h1 className=" justify-start mt-11  border-orange-500 border-b-4 rounded font-medium text-lg">
```suggestion
        <h1 className=" justify-start mt-11  border-orange-500 border-b-4  font-medium text-lg">
```

2023-07-27 18:09 UTC, joacoc commented on app/components/formuserinformation.js
> +        <h1 className="font-medium text-lg mt-1 ml-9 border-orange-500 border-b-4 rounded">
```suggestion
        <h1 className="font-medium text-lg mt-1 ml-9 border-orange-500 border-b-4">
```

2023-07-27 18:09 UTC, joacoc commented on app/components/formuserinformation.js
> +            <h1 className="font-medium text-lg ml-9 border-orange-500 border-b-4 rounded">
```suggestion
            <h1 className="font-medium text-lg ml-9 border-orange-500 border-b-4">
```

2023-07-27 18:09 UTC, joacoc commented
Fixate que te quedaron dos lineas grises en este (debería haber una sola): 
<img width="517" alt="Screenshot 2023-07-27 at 20 09 17" src="https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/11491779/13f97371-15fa-4500-915f-3facc7d95acc">

2023-07-27 18:12 UTC, joacoc commented
Mañana tomate el tiempo de solucionar este:
<img width="253" alt="Screenshot 2023-07-27 at 20 10 18" src="https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/11491779/3ae9e5f2-8176-4668-ae34-7094299caa83">

Y los errores que aparecen en el checkout form:
<img width="212" alt="Screenshot 2023-07-27 at 20 10 46" src="https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/11491779/87b689a4-7d33-4cc1-80e5-3e72e0d7a1a1">

Y algún icono mas divertido! (Busca "ticket" en [Heroicons](https://heroicons.com) o el emoji de 🎟️, el ticket de charley en la fabrica de chocolates)
<img width="305" alt="Screenshot 2023-07-27 at 20 11 06" src="https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/11491779/62bf831c-c7a1-4bb1-9b03-05e1779dff22">

2023-07-27 18:12 UTC, joacoc commented
El lunes es hora de arrancar el backend!

2023-07-27 20:51 UTC, SG-SantiagoGilgorri commented
Amigoo!!!

1ro: fijate lo del input del modal a ver si se soluciono.

2do: esos 3 errores me los tira desde la primera pagina, necesitaria verlo con vos porque es un problema de hyrdation, lei ahi un poco la documentacion de nextJS y consulte ChatGPT pero no encuentro la raiz del problema

3ro: decime el icono si esta un poco mas amigable. En heroicons hay uno solo de ticket y es una muerte jejeje

4ro: elimine una de las rayas que sobraba en el summary

2023-07-27 21:58 UTC, joacoc commented
@SG-SantiagoGilgorri Me encanto el icono!!

2023-07-27 22:01 UTC, joacoc commented
El icono esta tan bueno que sin el "Ticket-App" queda excelente! Fletaselo y mergea.
<img width="237" alt="Screenshot 2023-07-27 at 23 59 27" src="https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/11491779/83877350-ac33-4756-87dd-8765128cc635">

Estos pull request que son largos y tenemos mucha discusión raramente los vas a tener en tu día a día en el laburo. Como nosotros tenemos tiempo, realmente podemos mejorar las cosas y dejarlas bien. A veces pasa igual cuando los temas se ponen picantes que los PR son así de largos, pero raramente suceden.

2023-07-27 22:01 UTC, joacoc approved these changes

2023-07-27 22:08 UTC, joacoc commented
```html
<img src="https://tickets-a3s27pajv-sg-santiagogilgorri.vercel.app/ticket.png" style="height: 50px; margin: auto;">
```
<img width="462" alt="Screenshot 2023-07-28 at 00 07 19" src="https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/11491779/24b3852f-c5fd-427e-a6c3-271664b07c60">
<img width="388" alt="Screenshot 2023-07-28 at 00 07 38" src="https://github.com/SG-SantiagoGilgorri/Tickets-App/assets/11491779/8ed3f8e2-29fe-4104-a420-1e2275b99408">

2023-07-28 13:17 UTC, merged